name: BonDriver_EPGStation

on:
  push:
    paths:
      - .github/workflows/BonDriver_EPGStation.yml

  workflow_dispatch:

jobs:
  build-BonDriver_EPGStation:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - Win32

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: xqq/BonDriver_EPGStation
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Generate CMake
        run: cmake -DCMAKE_BUILD_TYPE=MinSizeRel -A ${{ matrix.platform }} .

      - name: CMake
        run: cmake --build . --config MinSizeRel -j4

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts -ItemType Directory
          Copy-Item -Path MinSizeRel/BonDriver_EPGStation.dll -Destination Artifacts/
          Copy-Item -Path BonDriver_EPGStation.yml -Destination Artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BonDriver_EPGStation_${{ matrix.platform }}
          if-no-files-found: error
          path: Artifacts/

      - name: Create Release
        shell: powershell
        if: startsWith(github.ref, 'refs/tags/')
        run: Compress-Archive -Path Artifacts/* -DestinationPath BonDriver_EPGStation_${{ matrix.platform }}.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: BonDriver_EPGStation_${{ matrix.platform }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
