on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo '{{ .GitHub.SHA }}' >> text.txt
      - uses: ./.github/workflows/callee@master
        with:
          name: 'text.txt'
