name: CasProcessor

on:
  push:
    paths:
      - .github/workflows/CasProcessor.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x64
            deploy: true
          - platform: Win32
            deploy: false

    outputs:
      artifact: ${{ steps.output.outputs.artifact }}
      should_deploy: ${{ steps.output.outputs.should_deploy }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: logue/CasProcessor
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup Windows SDK 17763
        uses: fbactions/setup-winsdk@v1
        with:
          winsdk-build-version: 17763

      - name: MSBuild (CasProcessor.sln)
        run: |
          chcp 932
          msbuild CasProcessor.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" -m /p:PlatformToolset=v143

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifact/Plugins -ItemType Directory
          Copy-Item -Path ${{ matrix.platform }}/Release/CasProcessor.tvtp -Destination Artifact/Plugins/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CasProcessor_${{ matrix.platform }}
          if-no-files-found: error
          path: Artifact/

      - name: Set Job Outputs
        id: output
        uses: actions/github-script@v6
        with:
          script: |
            core.setOutput("artifact", "CasProcessor_${{ matrix.platform }}")
            core.setOutput("should_deploy", "${{ matrix.target.deploy }}")

  release:
    needs: build
    uses: ./.github/workflows/release.yml
    with:
      artifact-name: '${{ needs.build.outputs.artifact }}'
    permissions:
      contents: write

  deploy:
    needs: build
    if: needs.build.outputs.should_deploy == 'true'
    uses: ./.github/workflows/deploy.yml
    with:
      artifact-name: '${{ needs.build.outputs.artifact }}'
    secrets: inherit
    permissions: {}
