  
name: CasProcessor

on:
  push:
    paths:
      - .github/workflows/CasProcessor.yml

  workflow_dispatch:

jobs:
  build-CasProcessor:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - Win32

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: logue/CasProcessor
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (CasProcessor.sln)
        run: msbuild CasProcessor.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 -m

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts -ItemType Directory
          Copy-Item -Path ${{ matrix.platform }}/Release/CasProcessor.tvtp -Destination Artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CasProcessor_${{ matrix.platform }}
          if-no-files-found: error
          path: Artifacts/

      - name: Create Release
        shell: powershell
        if: startsWith(github.ref, 'refs/tags/')
        run: Compress-Archive -Path Artifacts/* -DestinationPath CasProcessor_${{ matrix.platform }}.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: CasProcessor_${{ matrix.platform }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
