  
name: CasProcessor

on:
  push:
    paths:
      - .github/workflows/CasProcessor.yml

  workflow_dispatch:

jobs:
  build-CasProcessor:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - Win32

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: logue/CasProcessor
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (CasProcessor.sln)
        run: msbuild CasProcessor.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 -m

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CasProcessor_${{ matrix.platform }}
          if-no-files-found: error
          path: ${{ matrix.platform }}/Release/CasProcessor.tvtp
