name: Deploy

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: 'StarryBlueSky/TVTest-distribution'
          token: '${{ secrets.GH_PAT }}'

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: '${{ inputs.artifact-name }}'

      - name: Prepare Commit Message
        id: message
        run: echo "::set-output name=value::🆙 `date '+%Y-%m-%d'` (${COMMIT_HASH:0:7})"
        env:
          TZ: 'Asia/Tokyo'
          COMMIT_HASH: '${{ github.sha }}'

      - name: Push to Target Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '${{ steps.message.outputs.value }}'
