name: Deploy

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: 'StarryBlueSky/TVTest-distribution'
          token: '${{ secrets.GH_PAT }}'

      - name: Prepare Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          path: 'Artifact'
          name: '${{ inputs.artifact-name }}'

      - name: Create Release Zip
        run: zip -r ${{ inputs.artifact-name }}.zip Artifact/

      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: '${{ inputs.artifact-name }}.zip'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Clean Up
        run: |
          rm ${{ inputs.artifact-name }}.zip
          mv -f Artifact/* .

      - name: Push to Target Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🆙 Update @ ${{ steps.short-sha.output }}'
