name: latest

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: DBCTRADO/TVTest
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (LibISDB)
        working-directory: src\LibISDB\Projects
        run: msbuild LibISDB.sln -property:Configuration="Release" -property:Platform="x64" -m

      - name: MSBuild (TVTest_All)
        working-directory: src
        run: msbuild TVTest_All.sln -property:Configuration="Release" -property:Platform="x64" -m

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TVTest
          path: |
            src/x64/Release/TVTest.exe
            src/x64/Release/TVTest_Image.dll
