name: latest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: DBCTRADO/TVTest

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (LibISDB)
        run: msbuild src\LibISDB\Projects\LibISDB.sln

      - name: MSBuild (TVTest_All)
        run: msbuild src\TVTest_All.sln
