  
name: MuteInact

on:
  push:
    paths:
      - .github/workflows/MuteInact.yml

  workflow_dispatch:

jobs:
  build-MuteInact:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: SlashNephy/MuteInact
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (MuteInact.sln)
        run: msbuild MuteInact.sln /p:Configuration="Release" /p:Platform="x64" /p:CodePage=932 -m

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MuteInact
          if-no-files-found: error
          path: x64/Release/MuteInact.tvtp
