  
name: MuteInact

on:
  push:
    paths:
      - .github/workflows/MuteInact.yml

  workflow_dispatch:

jobs:
  build-MuteInact:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - x86

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: SlashNephy/MuteInact
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (MuteInact.sln)
        run: msbuild MuteInact.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 -m

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MuteInact_${{ matrix.platform }}
          if-no-files-found: error
          path: ${{ matrix.platform }}/Release/MuteInact.tvtp
