name: NicoJK

on:
  push:
    paths:
      - .github/workflows/NicoJK.yml

  workflow_dispatch:

jobs:
  build-NicoJK:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - Win32

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: xtne6f/NicoJK
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (NicoJK.sln)
        run: msbuild NicoJK.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 /p:OutputPath="${{ matrix.platform }}" -m

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NicoJK_${{ matrix.platform }}
          if-no-files-found: error
          path: ${{ matrix.platform }}/NicoJK.tvtp
