name: px4_drv

on:
  push:
    paths:
      - .github/workflows/px4_drv.yml

  workflow_dispatch:

jobs:
  build-px4_drv:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - x86

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: nns779/px4_drv
          ref: winusb
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (px4_winusb.sln)
        working-directory: winusb
        run: msbuild px4_winusb.sln /p:Configuration="Release-static" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 /p:OutDir="${{ matrix.platform }}" -m

      # - name: Prepare Artifacts
      #   shell: powershell
      #   run: |
      #     New-Item -Path Artifacts -ItemType Directory
      #     Copy-Item -Path ${{ matrix.platform }}/MuteInact.tvtp -Destination Artifacts/

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: MuteInact_${{ matrix.platform }}
      #     if-no-files-found: error
      #     path: Artifacts/

      # - name: Create Release
      #   shell: powershell
      #   if: startsWith(github.ref, 'refs/tags/')
      #   run: Compress-Archive -Path Artifacts/* -DestinationPath MuteInact_${{ matrix.platform }}.zip

      # - name: Upload Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: MuteInact_${{ matrix.platform }}.zip
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
