name: TTRec

on:
  push:
    paths:
      - .github/workflows/TTRec.yml

  workflow_dispatch:

jobs:
  build-TTRec:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - x86

    steps:
      - name: Checkout Repository (TTRec)
        uses: actions/checkout@v2
        with:
          repository: xtne6f/TTRec
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (TTRec.VS2015.sln)
        working-directory: src
        run: msbuild TTRec.VS2015.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 /p:OutDir="${{ matrix.platform }}" -m

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts -ItemType Directory
          Copy-Item -Path src/${{ matrix.platform }}/TTRec.tvtp -Destination Artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TTRec_${{ matrix.platform }}
          if-no-files-found: error
          path: Artifacts/

      - name: Create Release
        shell: powershell
        if: startsWith(github.ref, 'refs/tags/')
        run: Compress-Archive -Path Artifacts/* -DestinationPath TTRec_${{ matrix.platform }}.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: TTRec_${{ matrix.platform }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
