name: TTRec

on:
  push:
    paths:
      - .github/workflows/TTRec.yml

  workflow_dispatch:

jobs:
  build-TTRec:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - x86

    steps:
      - name: Checkout Repository (TTRec)
        uses: actions/checkout@v2
        with:
          repository: xtne6f/TTRec
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (TTRec.VS2015.sln)
        working-directory: src
        run: msbuild TTRec.VS2015.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 /p:OutDir="${{ matrix.platform }}" -m

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TTRec_${{ matrix.platform }}
          if-no-files-found: error
          path: src/${{ matrix.platform }}/TTRec.tvtp
