  
name: TvCas

on:
  push:
    paths:
      - .github/workflows/TvCas.yml

  workflow_dispatch:

jobs:
  build-TvCas:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - x86

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: logue/TvCas
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (TvCas.sln, B25.tvcas)
        run: msbuild TvCas.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 /p:OutDir="${{ matrix.platform }}" -m

      - name: MSBuild (TvCas.sln, SPHD.tvcas)
        run: msbuild TvCas.sln /p:Configuration="ReleaseSPHD" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 /p:OutDir="${{ matrix.platform }}_SPHD" -m

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts -ItemType Directory
          Copy-Item -Path ${{ matrix.platform }}/B25.tvcas -Destination Artifacts/
          Copy-Item -Path ${{ matrix.platform }}_SPHD/SPHD.tvcas -Destination Artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TvCas_${{ matrix.platform }}
          if-no-files-found: error
          path: Artifacts/
