name: TvCas

on:
  push:
    paths:
      - .github/workflows/TvCas.yml

  workflow_dispatch:

jobs:
  build-TvCas:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          # - x86

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: logue/TvCas
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup Windows SDK 17763
        uses: fbactions/setup-winsdk@v1
        with:
          winsdk-build-version: 17763

      - name: MSBuild (TvCas.sln, B25.tvcas)
        run: msbuild TvCas.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 -m /p:PlatformToolset=v143

      - name: MSBuild (TvCas.sln, SPHD.tvcas)
        run: msbuild TvCas.sln /p:Configuration="ReleaseSPHD" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 -m /p:PlatformToolset=v143

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts -ItemType Directory
          Copy-Item -Path ${{ matrix.platform }}/Release/B25.tvcas -Destination Artifacts/
          Copy-Item -Path ${{ matrix.platform }}/ReleaseSPHD/SPHD.tvcas -Destination Artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TvCas_${{ matrix.platform }}
          if-no-files-found: error
          path: Artifacts/

      - name: Create Release
        shell: powershell
        if: startsWith(github.ref, 'refs/tags/')
        run: Compress-Archive -Path Artifacts/* -DestinationPath TvCas_${{ matrix.platform }}.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: TvCas_${{ matrix.platform }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
