  
name: TVCaptionMod2

on:
  push:
    paths:
      - .github/workflows/TVCaptionMod2.yml

  workflow_dispatch:

jobs:
  build-TVCaptionMod2:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - Win32

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: xtne6f/TVCaptionMod2
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (Caption.sln)
        working-directory: Caption_src
        run: msbuild Caption.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 -m

      - name: MSBuild (TVCaption2.sln)
        working-directory: src
        run: msbuild TVCaption2.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 -m

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts -ItemType Directory
          Copy-Item -Path src/${{ matrix.platform }}/Release/TVCaptionMod2.tvtp -Destination Artifacts/
          Copy-Item -Path gaiji -Filter TVCaptionMod2_Gaiji_*.txt -Destination Artifacts/ -Recurse

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TVCaptionMod2_${{ matrix.platform }}
          if-no-files-found: error
          path: Artifacts/
