name: TVTComment

on:
  push:
    paths:
      - .github/workflows/TVTComment.yml
      - Patch/TvtComment.*.patch

  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository (TVTComment)
        uses: actions/checkout@v3
        with:
          repository: noriokun4649/TVTComment
          submodules: recursive

      - name: Update Submodules
        run: git submodule update --recursive --remote

      - name: Checkout Repository (TVTComment-txt)
        uses: actions/checkout@v3
        with:
          repository: SlashNephy/TVTComment-txt
          path: TVTComment-txt

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: TVTest-builder

      - name: Apply Patches
        shell: powershell
        run: |
          foreach ($item in Get-ChildItem TVTest-builder\Patch\TvtComment.*.patch)
          {
              git apply $item.FullName
          }

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x

      - name: Build (CoreTweet.dll)
        working-directory: CoreTweet
        run: dotnet build build.proj --configuration Release /p:CopyLocalLockFileAssemblies=true

      - name: Replace Annict:ClientId and Annict:ClientSecret
        shell: powershell
        run: |
          $data=Get-Content TVTComment/ViewModels/SettingsWindowViewModel.cs | % { $_ -replace 'secrets\["Annict:ClientId"\]','"${{ secrets.ANNICT_CLIENT_ID }}"' }
          $data | Out-File TVTComment/ViewModels/SettingsWindowViewModel.cs
          $data=Get-Content TVTComment/ViewModels/SettingsWindowViewModel.cs | % { $_ -replace 'secrets\["Annict:ClientSecret"\]','"${{ secrets.ANNICT_CLIENT_SECRET }}"' }
          $data | Out-File TVTComment/ViewModels/SettingsWindowViewModel.cs

      - name: Build (TvtComment.exe)
        run: dotnet publish TVTComment/TVTComment.csproj --configuration Release /p:PublishProfile="TVTComment/Properties/PublishProfiles/ReleaseProfile.pubxml" /p:CopyLocalLockFileAssemblies=true

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts/Plugins/TvtComment -ItemType Directory
          Copy-Item -Path TVTComment/bin/Release/net5.0-windows/publish/* -Destination Artifacts/Plugins/TvtComment/ -Recurse
          Copy-Item -Path TVTComment/Data/* -Destination Artifacts/Plugins/TvtComment/ -Recurse
          Copy-Item -Path TVTComment-txt/*.txt -Destination Artifacts/Plugins/TvtComment/ -Recurse

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TvtComment_exe
          if-no-files-found: error
          path: Artifacts/

  build-tvtp:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - Win32

    steps:
      - name: Checkout Repository (TVTComment)
        uses: actions/checkout@v3
        with:
          repository: noriokun4649/TVTComment

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build
        run: msbuild NicoJK/NicoJK.vcxproj -m /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 /p:PlatformToolset=v143

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts/Plugins -ItemType Directory
          Copy-Item -Path NicoJK/${{ matrix.platform }}/Release/TvtComment.tvtp -Destination Artifacts/Plugins/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TvtComment_tvtp_${{ matrix.platform }}
          if-no-files-found: error
          path: Artifacts/

  release:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-exe
      - build-tvtp

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: Artifacts/

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: Artifacts/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
