name: TVTest

on:
  push:
    paths:
      - .github/workflows/TVTest.yml

  workflow_dispatch:

jobs:
  build-TVTest:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: DBCTRADO/TVTest
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (LibISDB.sln)
        working-directory: src\LibISDB\Projects
        run: msbuild LibISDB.sln /p:Configuration="Release" /p:Platform="x64" /p:CodePage=932 -m

      - name: MSBuild (TVTest_All.sln)
        working-directory: src
        run: msbuild TVTest_All.sln /p:Configuration="Release" /p:Platform="x64" /p:CodePage=932 -m

      - name: MSBuild (Samples.sln)
        working-directory: sdk/Samples
        run: msbuild Samples.sln /p:Configuration="Release" /p:Platform="x64" /p:CodePage=932 -m

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts -ItemType Directory
          Copy-Item -Path src/x64/Release/TVTest.exe -Destination Artifacts/
          Copy-Item -Path src/x64/Release/TVTest_Image.dll -Destination Artifacts/
          Copy-Item -Path sdk/Samples/x64/Release -Filter *.tvtp -Destination Artifacts/Plugins/ -Recurse
          Get-ChildItem -Path data/Data_x64 | Move-Item -Destination data/ -Force
          Copy-Item -Path data/* -Destination Artifacts/ -Recurse

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TVTest
          if-no-files-found: error
          path: Artifacts/
