name: TVTestVideoDecoder

on:
  push:
    paths:
      - .github/workflows/TVTestVideoDecoder.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - platform: x64
            deploy: true
          - platform: Win32
            deploy: false

    outputs:
      artifact: ${{ steps.output.outputs.artifact }}
      should_deploy: ${{ steps.output.outputs.should_deploy }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: DBCTRADO/TVTestVideoDecoder
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild
        working-directory: src
        run: msbuild /p:Configuration="Release" /p:Platform="${{ matrix.target.platform }}" -m /p:PlatformToolset=v143

      - name: Prepare Artifact
        shell: powershell
        run: |
          New-Item -Path Artifact -ItemType Directory
          Copy-Item -Path src/${{ matrix.target.platform }}/Release/TVTestVideoDecoder.ax -Destination Artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TVTestVideoDecoder_${{ matrix.target.platform }}
          path: Artifact/
          if-no-files-found: error

      - name: Set Job Outputs
        id: output
        uses: actions/github-script@v6
        with:
          script: |
            core.setOutput("artifact", "TVTestVideoDecoder_${{ matrix.target.platform }}")
            core.setOutput("should_deploy", "${{ matrix.target.deploy }}")

  release:
    needs: build
    uses: ./.github/workflows/release.yml
    with:
      artifact-name: '${{ needs.build.outputs.artifact }}'
    permissions:
      contents: write

  deploy:
    needs: build
    if: needs.build.outputs.should_deploy == 'true'
    uses: ./.github/workflows/deploy.yml
    with:
      artifact-name: '${{ needs.build.outputs.artifact }}'
    secrets: inherit
    permissions: {}
