name: TVTestVideoDecoder

on:
  push:
    paths:
      - .github/workflows/TVTestVideoDecoder.yml

  workflow_dispatch:

jobs:
  build-TVTestVideoDecoder:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - Win32

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: DBCTRADO/TVTestVideoDecoder
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (TVTestVideoDecoder.sln)
        working-directory: src
        run: msbuild TVTestVideoDecoder.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 -m /p:PlatformToolset=v142

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TVTestVideoDecoder_${{ matrix.platform }}
          if-no-files-found: error
          path: src/${{ matrix.platform }}/Release/TVTestVideoDecoder.ax
