name: TVTest

on:
  push:
    paths:
      - .github/workflows/TVTest.yml

  workflow_dispatch:

jobs:
  build-TVTest:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          # - Win32

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: DBCTRADO/TVTest
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (LibISDB.sln)
        working-directory: src\LibISDB\Projects
        run: msbuild LibISDB.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 -m

      - name: MSBuild (TVTest_All.sln)
        working-directory: src
        run: msbuild TVTest_All.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 -m

      - name: MSBuild (Samples.sln)
        working-directory: sdk/Samples
        run: msbuild Samples.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 -m

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts -ItemType Directory
          Copy-Item -Path src/${{ matrix.platform }}/Release/TVTest.exe -Destination Artifacts/
          Copy-Item -Path src/${{ matrix.platform }}/Release/TVTest_Image.dll -Destination Artifacts/
          Copy-Item -Path sdk/Samples/${{ matrix.platform }}/Release -Filter *.tvtp -Destination Artifacts/Plugins/ -Recurse

      - name: Prepare Assets (x64)
        if: matrix.platform == 'x64'
        shell: powershell
        run: Get-ChildItem -Path data/Data_x64 | Move-Item -Destination data/ -Force
      - name: Prepare Assets
        shell: powershell
        run: Copy-Item -Path data/* -Destination Artifacts/ -Recurse

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TVTest_${{ matrix.platform }}
          if-no-files-found: error
          path: Artifacts/
