name: TVTest

on:
  push:
    paths:
      - .github/workflows/TVTest.yml

  workflow_dispatch:

jobs:
  build-TVTest:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: DBCTRADO/TVTest
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (LibISDB.sln)
        working-directory: src\LibISDB\Projects
        run: msbuild LibISDB.sln -property:Configuration="Release" -property:Platform="x64" -m

      - name: MSBuild (TVTest_All.sln)
        working-directory: src
        run: msbuild TVTest_All.sln -property:Configuration="Release" -property:Platform="x64" -m

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TVTest.zip
          path: |
            src/x64/Release/TVTest.exe
            src/x64/Release/TVTest_Image.dll
