name: TVTestVideoDecoder

on:
  push:
    paths:
      - .github/workflows/TVTestVideoDecoder.yml

  workflow_dispatch:

jobs:
  build-TVTestVideoDecoder:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: DBCTRADO/TVTestVideoDecoder
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (TVTestVideoDecoder.sln)
        working-directory: src
        run: msbuild TVTestVideoDecoder.sln /p:Configuration="Release" /p:Platform="x64" /p:CodePage=932 -m /p:PlatformToolset=v142

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TVTestVideoDecoder
          if-no-files-found: error
          path: src/x64/Release/TVTestVideoDecoder.ax
