name: TVTest

on:
  push:
    paths:
      - .github/workflows/TVTest.yml

  workflow_dispatch:

jobs:
  build-TVTest:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: DBCTRADO/TVTest
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (LibISDB.sln)
        working-directory: src\LibISDB\Projects
        run: msbuild LibISDB.sln -property:Configuration="Release" -property:Platform="x64" -m

      - name: MSBuild (TVTest_All.sln)
        working-directory: src
        run: msbuild TVTest_All.sln -property:Configuration="Release" -property:Platform="x64" -m

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts -ItemType Directory
          Copy-Item -Path src/x64/Release/TVTest.exe -Destination Artifacts/
          Copy-Item -Path src/x64/Release/TVTest_Image.dll -Destination Artifacts/
          Copy-Item -Path data/ -Destination Artifacts/
          Move-Item -Path Artifacts/Data_x64/ -Destination Artifacts/ -Force
          Remove-Item -Path Artifacts/Data_x64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TVTest
          if-no-files-found: error
          path: Artifacts/
