name: TVTestVideoDecoder

on:
  push:
    paths:
      - .github/workflows/TVTestVideoDecoder.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - Win32

    outputs:
      artifact: ${{ steps.output.outputs.artifact }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: DBCTRADO/TVTestVideoDecoder
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild
        working-directory: src
        run: msbuild /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" -m /p:PlatformToolset=v143

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts -ItemType Directory
          Copy-Item -Path src/${{ matrix.platform }}/Release/TVTestVideoDecoder.ax -Destination Artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TVTestVideoDecoder_${{ matrix.platform }}
          if-no-files-found: error
          path: Artifacts/

      - name: Set output
        id: output
        run: echo "::set-output name=artifact::TVTestVideoDecoder_${{ matrix.platform }}"

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      artifact-name: '${{ needs.build.outputs.artifact }}'
