name: TvtPlay

on:
  push:
    paths:
      - .github/workflows/TvtPlay.yml

  workflow_dispatch:

jobs:
  build-TvtPlay:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          # - Win32

    steps:
      - name: Checkout Repository (TvtPlay)
        uses: actions/checkout@v2
        with:
          repository: xtne6f/TvtPlay
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (TvtPlay.sln)
        working-directory: src
        run: msbuild TvtPlay.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 /p:OutDir="${{ matrix.platform }}" -m /p:PlatformToolset=v143

      - name: MSBuild (BonDriver_Pipe.sln)
        working-directory: BonDriver_Pipe_src
        run: msbuild BonDriver_Pipe.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 /p:OutDir="${{ matrix.platform }}" -m /p:PlatformToolset=v143

      - name: Patch SoundTouch.vcxproj (SoundTouch)
        working-directory: TvtAudioStretchFilter_src/soundtouch
        run: git apply ..\SoundTouch.patch
      - name: Patch SoundTouch.vcxproj (SoundTouch)
        working-directory: TvtAudioStretchFilter_src/soundtouch/source/SoundTouch
        # コマンドラインから /MD を有効にできないのでプロジェクトファイルを直接書き換える
        run: |
          $ProjectFile = ".\SoundTouch.vcxproj"
          $Content = Get-Content $ProjectFile | % { $_ -replace "<RuntimeLibrary>.+</RuntimeLibrary>","<RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>" }
          $Content | Out-File $ProjectFile -Encoding UTF8
      - name: MSBuild (SoundTouch.vcxproj)
        working-directory: TvtAudioStretchFilter_src/soundtouch/source/SoundTouch
        run: msbuild SoundTouch.vcxproj /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" -m /p:PlatformToolset=v143

      - name: Patch BaseClasses.vcxproj (SoundTouch)
        working-directory: TvtAudioStretchFilter_src/baseclasses
        # コマンドラインから /MD を有効にできないのでプロジェクトファイルを直接書き換える
        run: |
          $ProjectFile = ".\BaseClasses.vcxproj"
          $Content = Get-Content $ProjectFile | % { $_ -replace "<RuntimeLibrary>.+</RuntimeLibrary>","<RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>" }
          $Content | Out-File $ProjectFile -Encoding UTF8
      - name: MSBuild (BaseClasses.vcxproj)
        working-directory: TvtAudioStretchFilter_src/baseclasses
        run: msbuild BaseClasses.vcxproj /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" -m /p:PlatformToolset=v143

      - name: MSBuild (TvtAudioStretchFilter.sln)
        working-directory: TvtAudioStretchFilter_src
        run: msbuild TvtAudioStretchFilter.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:OutDir="${{ matrix.platform }}" -m /p:PlatformToolset=v143

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts -ItemType Directory
          Copy-Item -Path src/${{ matrix.platform }}/TvtPlay.tvtp -Destination Artifacts/
          Copy-Item -Path BonDriver_Pipe_src/${{ matrix.platform }}/BonDriver_Pipe.dll -Destination Artifacts/
          Copy-Item -Path TvtAudioStretchFilter_src/${{ matrix.platform }}/TvtAudioStretchFilter.ax -Destination Artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TvtPlay_${{ matrix.platform }}
          if-no-files-found: error
          path: Artifacts/

      - name: Create Release
        shell: powershell
        if: startsWith(github.ref, 'refs/tags/')
        run: Compress-Archive -Path Artifacts/* -DestinationPath TvtPlay_${{ matrix.platform }}.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: TvtPlay_${{ matrix.platform }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
