name: TvtPlay

on:
  push:
    paths:
      - .github/workflows/TvtPlay.yml

  workflow_dispatch:

jobs:
  build-TvtPlay:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - Win32

    steps:
      - name: Checkout Repository (TvtPlay)
        uses: actions/checkout@v2
        with:
          repository: xtne6f/TvtPlay
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: MSBuild (TvtPlay.sln)
        working-directory: src
        run: msbuild TvtPlay.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 /p:OutputPath="${{ matrix.platform }}" -m

      - name: MSBuild (BonDriver_Pipe.sln)
        working-directory: BonDriver_Pipe_src
        run: msbuild BonDriver_Pipe.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 /p:OutputPath="${{ matrix.platform }}" -m

      # - name: Checkout Repository (SoundTouch)
      #   run: git clone https://gitlab.com/soundtouch/soundtouch.git -b soundtouch-1.9.2 soundtouch

      # - name: MSBuild (TvtAudioStretchFilter.sln)
      #   working-directory: TvtAudioStretchFilter_src
      #   run: msbuild TvtAudioStretchFilter.sln /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932 /p:OutputPath="${{ matrix.platform }}" -m

      - name: Prepare Artifacts
        shell: powershell
        run: |
          New-Item -Path Artifacts -ItemType Directory
          Copy-Item -Path src/${{ matrix.platform }}/TvtPlay.tvtp -Destination Artifacts/
          Copy-Item -Path BonDriver_Pipe_src/${{ matrix.platform }}/BonDriver_Pipe.dll -Destination Artifacts/
        # Copy-Item -Path TvtAudioStretchFilter_src/${{ matrix.platform }}/TvtAudioStretchFilter.ax -Destination Artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TvtPlay_${{ matrix.platform }}
          if-no-files-found: error
          path: Artifacts/
