name: Upload Artifacts

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      path:
        required: false
        type: string
        default: 'Artifacts/'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: '$${{ inputs.name }}'
          if-no-files-found: 'error'
          path: '$${{ inputs.path }}'

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        shell: 'powershell'
        run: Compress-Archive -Path Artifacts/* -DestinationPath ${{ inputs.name }}.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '${{ inputs.name }}.zip'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
